### ISSUE TITLE
Overlay not aligned

### ISSUE THREAD

**Issue by ezioauditore1017** [MeusRex/pf2e-chex#1] opened 2024-01-16 19:42 UTC
![image](https://github.com/MeusRex/pf2e-chex/assets/17515764/b643c6b1-c9d7-4843-9892-45a8a7f46b2c)

![image](https://github.com/MeusRex/pf2e-chex/assets/17515764/ba1203b5-0907-4912-adcb-bb459b5f13f3)

The overlay doesn't seem to be aligned with the map. I asked on your reddit post and you said to post pictures if I was still having issues.

**Comment by MeusRex** [comment] 2024-01-19 09:35
Sorry, I must have disabled the notifications at some point and didn't notice that someone created an issue.
Thanks for the screenshot. That is wierd. I'll have to try and reproduce this issue. For some reason the highlight layer seems to be off. Which is rather wierd, since that is a foundry feature and you just give the coordinates of a hex. -> E.g. the drawn grid and the highlight layer aren't aligned anymore.
Do you have the same issue if you create a new scene? Or only if you add it to this specific scene?
Do you have any mods that might modify the grid or highlight layer. I can see that you have 3D Canvas at least. Was this ever active on this scene?

**Comment by MeusRex** [comment] 2024-01-19 09:40
Also, aren't you also running into this issue?

https://github.com/MeusRex/pf2e-chex/issues/2

**Comment by Ackerfe** [comment] 2024-01-19 21:06
> Also, aren't you also running into this issue?
> 
> #2

Nope, this hasn't been an issue at all for me, I wasn't having it even when I had my hex grid size set to 50, I set it to 100 in order to use Chex and just disabled and re-enabled chex on the scene and it's working fine, no misalignment to be seen

**Comment by Ackerfe** [comment] 2024-01-19 21:19
Wondering if the width and height being at a weird resolution that is not 16:9 might have something to do with it, though I haven't seen anything that might get impacted by that in your code and hexes are perfectly tileable so at most he should get some cut hexes at the edges of the map and not a misalignment

**Comment by ezioauditore1017** [comment] 2024-01-19 21:46
> Sorry, I must have disabled the notifications at some point and didn't notice that someone created an issue. Thanks for the screenshot. That is wierd. I'll have to try and reproduce this issue. For some reason the highlight layer seems to be off. Which is rather wierd, since that is a foundry feature and you just give the coordinates of a hex. -> E.g. the drawn grid and the highlight layer aren't aligned anymore. Do you have the same issue if you create a new scene? Or only if you add it to this specific scene? Do you have any mods that might modify the grid or highlight layer. I can see that you have 3D Canvas at least. Was this ever active on this scene?

I recreated the scene and it seemed to work? I think I enabled 3d canvas on it at some point. That might have caused an issue.

**Comment by MeusRex** [comment] 2024-01-20 12:29
I'll close this issue then. As it works with a fresh scene. So it is most likely that some other module modified the highlight layer.

**Closed by MeusRex** 2024-01-20 12:29 UTC
